#! /bin/bash

# Copyright (c) 2017 Agnibho Mondal
# All rights reserved
#
# This file is part of ImageCap.
#
# ImageCap is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# ImageCap is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.  See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# ImageCap.  If not, see <http://www.gnu.org/licenses/>.
#
# Agnibho Mondal
# contact@agnibho.com
# www.agnibho.com

SELF="$(realpath "$0")";
ARG="$(echo $1 | sed "s/^file:\/\///g")";
DIR="$(dirname "$ARG")";
if [ -n "$ARG" ];then
	IMG="$DIR/$(basename "$ARG")";
fi

function update(){
	DATA=$(exiftool -S -s -b -comment "$1");
	DATA=$(echo -n "$DATA"|zenity --text-info --editable --title="Edit Caption" --ok-label="Update");
	if [ "$?" = "0" ];then
		exiftool -overwrite_original_in_place -comment="$DATA" "$1";
	fi
}

function view(){
	if [ -n "$IMG" ];then
		feh -q --action1 ";$SELF -e '%f'" --info "exiftool -S -s -b -comment '%f'" --scale-down --draw-tinted --start-at "$IMG" "$DIR";
	else
		feh -q --action1 ";$SELF -e '%f'" --info "exiftool -S -s -b -comment '%f'" --scale-down --draw-tinted "$DIR";
	fi
}

if [ "$1" == "-e" ];then
	update "$2";
else
	view "$1";
fi
